// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.4.0 <0.9.0;
 
contract Immutable{
    /* Immutable:  Variables declared as immutable are a bit less restricted than those declared as constant.
    a) Immutable variables can be assigned an arbitrary value in the constructor of the contract
         or atthe point of their declaration.
    b) They cannot be read during construction time and can only be assigned once.
    c) Contract creation code generated by compiler will modify the runtime code before 
         itis returned by replacing all references to immutables by the values assigned to the them.
    */
    // immutable variable Are like constant It's only once we deploy when contract was deploy....
    // but you can be change later on...
  


    // coding convention to uppercase constant variables
    address public immutable MY_ADDRESS; 
    uint public immutable MY_UINT;
    uint public immutable DATE_OF_BIRTH = 13071980;// DDMMYYYY

    constructor(uint _myUint) {
        MY_ADDRESS = msg.sender;
        MY_UINT = _myUint;
    }
}

